#!/bin/sh
echo "Started '$0' script from initramfs."

trap 'exec /bin/sh' INT EXIT

mount -n -t devtmpfs devtmpfs /dev
mount -n -t proc none /proc
mount -n -t tmpfs none /run
mount -n -t sysfs none /sys

set -- $(cat /proc/cmdline)

rootwait=true # defaults to off in the kernel, I think it's more useful on
for arg; do
    case "$arg" in
    root=LABEL=*)
        if [ x"$root_type" != x ]; then
            echo "Warning, multiple root= specified, using latest."
        fi
        root_type=label
        root="${arg#root=LABEL=}"
        ;;
    root=UUID=*)
        if [ x"$root_type" != x ]; then
            echo "Warning, multiple root= specified, using latest."
        fi
        root_type=uuid
        root="${arg#root=UUID=}"
        ;;
    root=*)
        if [ x"$root_type" != x ]; then
            echo "Warning, multiple root= specified, using latest."
        fi
        root_type=disk
        root="${arg#root=}"
        ;;
    rootflags=*)
        if [ x"$rootflags" != x ]; then
            echo "Warning, multiple rootflags= specified, using latest."
        fi
        rootflags=",${arg#rootflags=}"
        ;;
    rootfstype=*)
        if [ x"$rootfstype" != x ]; then
            echo "Warning, multiple rootfstype= specified, using latest."
        fi
        rootfstype="${arg#rootfstype=}"
        ;;
    rootdelay=*)
        if [ x"$rootdelay" != x ]; then
            echo "Warning, multiple rootdelay= specified, using latest."
        fi
        rootdelay="${arg#rootdelay=}"
        ;;
    rootwait)
        rootwait=true
        ;;
    norootwait)
        rootwait=false
        ;;
    ro)
        ro=ro
        ;;
    rw)
        ro=rw
        ;;
    init=*)
        init="${arg#init=}"
        ;;
    esac
done


if [ x"$rootdelay" != x ]; then
    sleep "$rootdelay"
fi

while true; do
    case "$root_type" in
    disk)
        if mount -n -t "${rootfstype}" -o "${ro-rw}""$rootflags" "$root" /mnt; then
            break
        else
            echo disk $root not found
            blkid
        fi
        ;;
    label)
        disk="$(findfs LABEL="$root")"
        if [ x"$disk" = x ]; then
            echo disk with label $root not found
            blkid
        else
            mount -n -t "${rootfstype}" -o "${ro-rw}""$rootflags" "$disk" /mnt && break
        fi
        ;;
    uuid)
        disk="$(findfs UUID="$root")"
        if [ x"$disk" = x ]; then
            echo disk with UUID $root not found
            blkid
        else
            mount -n -t "${rootfstype}" -o "${ro-rw}""$rootflags" "$disk" /mnt && break
        fi
        ;;
    '')
        echo "Error, no root specified"
        exit 1
        ;;
    esac
    if "$rootwait"; then
        echo Trying again in 0.5 seconds
        sleep 0.5
    fi
done

exec switch_root /mnt "${init-/sbin/init}"
