kind: stack

depends:
- filename: base.bst
- filename: desktop-platform.bst
- filename: desktop/desktop-file-utils.bst
- filename: desktop/gtk-doc.bst
- filename: desktop/itstools.bst
- filename: desktop/jq.bst
- filename: desktop/mercurial.bst
- filename: desktop/wayland-protocols.bst
- filename: desktop/xorg-proto-xcb.bst
- filename: desktop/xorg-proto-xorgproto.bst
- filename: desktop/xorg-util-macros.bst
