kind: stack
depends:
  - filename: basesdk.bst
  - filename: basesdk-debug.bst
  - filename: baseplatform.bst
  - filename: sdk.bst
  - filename: sdk-debug.bst
  - filename: sdk-docs.bst
  - filename: sdk-locale.bst
  - filename: platform.bst
  - filename: platform-locale.bst
  - filename: platform-arch-libs.bst
  - filename: platform-arch-libs-debug.bst
  - filename: glxinfo.bst
  - filename: glxinfo-debug.bst
