#!/bin/sh
timestamp=$(git log -1 --format="%at" ${CI_COMMIT_SHA})
cat >"$1" <<EOF
variables:
    runtime-version: '$(git describe | sed 's/^freedesktop-sdk-//')'
    runtime-version-date: $(date -d @"$timestamp" -Idate)
EOF
