kind: check_forbidden

build-depends:
- sdk.bst

config:
  forbidden:
  - components/apparmor.bst
  - components/avahi.bst
  - components/ccid.bst
  - components/dracut.bst
  - components/gamemode.bst
  - components/iproute2.bst
  - components/libapparmor.bst
  - components/linux-firmware.bst
  - components/linux-pam.bst
  - components/linux.bst
  - components/llvm.bst
  - components/open-iscsi.bst
  - components/openssh-systemd.bst
  - components/ostree.bst
  - components/pcsc-lite.bst
  - components/pipewire-daemon.bst
  - components/plymouth.bst
  - components/rtkit.bst
  - components/rust.bst
  - components/steam-devices.bst
  - components/sudo.bst
  - components/systemd.bst
  - components/vim.bst
  - components/weston.bst
  - components/wireless-regdb-bin.bst
  - components/wpa-supplicant.bst
  - components/xdg-desktop-portal.bst
  - components/xfsprogs.bst
  - components/xwayland.bst
